export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const LOGGED_IN_REQUEST = "LOGGED_IN_REQUEST";
export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
